// <auto-generated />
using System;
using DairyBidding.BiddingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DairyBidding.BiddingService.Data.Migrations
{
    [DbContext(typeof(BiddingDbContext))]
    [Migration("20260701065235_AddProcessedMessageUniqueIndexAndSnakeCase")]
    partial class AddProcessedMessageUniqueIndexAndSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DairyBidding.BiddingService.Data.AuctionBidReadModel", b =>
                {
                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<decimal>("HighestBidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("highest_bid_amount");

                    b.Property<string>("HighestBidderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("highest_bidder_id");

                    b.Property<int>("TotalBids")
                        .HasColumnType("integer")
                        .HasColumnName("total_bids");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AuctionId")
                        .HasName("pk_auction_bid_read_models");

                    b.ToTable("auction_bid_read_models", (string)null);
                });

            modelBuilder.Entity("DairyBidding.BiddingService.Data.AuctionReadModel", b =>
                {
                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AuctionId")
                        .HasName("pk_auction_read_models");

                    b.ToTable("auction_read_models", (string)null);
                });

            modelBuilder.Entity("DairyBidding.BiddingService.Data.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("AuctionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<string>("BidderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bidder_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("BidderId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_bids_bidder_id_idempotency_key");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("DairyBidding.BiddingService.Data.ProcessedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_processed_messages");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_processed_messages_message_id");

                    b.ToTable("processed_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
